### PR TITLE
Change config directory to ~/.config/lwsm

### PR DESCRIPTION
**Pull request by ybnd**
& move contents of legacy config directory ~/.lwsm if present

### CODE REVIEW

**Comment by johannesjo** [comment]
That's great! Love it! Thank you very much!

**Comment by allentiak** [comment]
@ybnd Thank you so much!

**Comment by johannesjo** [comment]
I had to revert the change because it breaks the gnome shell extension.  I'll reintroduce the changes once the update for the shell extension is published (which can take some time unfortunately). Meanwhile you can use 3.2.1.

**Comment by allentiak** [comment]
Sure. Thanks for the heads up, @johannesjo !

**Comment by allentiak** [comment]
> I'll reintroduce the changes once the update for the shell extension is published (which can take some time unfortunately).

I'll open a new bug for this, just to keep it alive.

**Comment by allentiak** [comment]
> I'll open a new bug for this, just to keep it alive.

@johannesjo I just found out you opened #70. No further tickets neeeded :-)

**Pull request merged**
