### PR TITLE
Fixed bug when moving applications to third or higher workspaces

### LINKED ISSUE #62: Doesn't put applications in the third workspace.
## Your Environment

* Version used: Latest
* Operating System and version: PopOS 19.10
* Desktop Environment: Gnome
* Node version: 12.16.1
* List of Applications that are open (lwsm save) or should be opened (lwsm restore): Unity hub, Clementine, Firefox, Monodevelop, terminal, gamehub

## Expected Behavior

* lwsm save with three different workspaces open
* lwsm restore with one workspace open
* all windows should reopen in all three workspaces respectively

## Current Behavior

* lwsm save with three diferent workspaces open
* lwsm restore with one workspace open
* workspace one and two configure themselves correctly, but all of the windows that should be in workspace three end up back in workspace one.

## Steps to Reproduce (for bugs)

1. Using gnome, have three workspaces open, with different windows in each, then type lwsm save in a terminal window
2. close all of the windows in each workspace, leaving you with no windows open
3. open a terminal and type lwsm restore

### PR DESCRIPTION
**Pull request by RodrigoATorres**
Fixed #62 

The bug was occurring because it was trying to move the windows to an workspace that did not exist yet.

To fix that I ordered the windows objects based on its workspace location, then moved them in that order. The Window Manager creates an additional workspace ever time a window is moved to the last one. The promises for each workspace were executed separately to make sure the Window Manager created the new workspace.

I also tried to set the _NET_NUMBER_OF_DESKTOPS to the number of desktops it would require, but it did not work. The documentation says the Window Manager may or may not honor the request.

I had to disable prettier, because it was making a lot of changes on the code.
It is my first contribution to a opensource project, so let me know if I should have done it differently.
Thanks for the project, it is awesome.

### CODE REVIEW

**Comment by johannesjo** [comment]
Thank you very much for your contribution! Much appreciated! I will add some comments to the code.

**Comment by johannesjo** [comment]
I am through with the review. Very smart solution! I am impressed!

**Comment by RodrigoATorres** [comment]
Thanks! I am glad to help

**Comment by johannesjo** [comment]
Would you like to address the things I mentioned in the review yourself or shall I do it? :)

**Comment by RodrigoATorres** [comment]
Where can I find the review? Tried to search on github docs how, but I couldn't find it.

**Comment by johannesjo** [comment]
https://github.com/johannesjo/linux-window-session-manager/pull/64/files

There are also comments above. Not a clue why you can't see them...

**Comment by RodrigoATorres** [comment]
Screenshot from 2020-04-07 22-26-53

I am sorry if I am being stupid (I am new here), but I really can't see it

**Comment by RodrigoATorres** [comment]
Anyway, feel free to make any changes.

**Comment by johannesjo** [comment]
My bad! Want aware that the review needs to be submitted...

**Comment by RodrigoATorres** [comment]
Thanks for the review, I have just added the commit.

**Comment by johannesjo** [comment]
Thank you very much! I will make a new release shortly!

**Pull request merged**
